// Code generated by controller-gen. DO NOT EDIT.
// Execute: make generate
// Este arquivo é gerado automaticamente pelo kubebuilder/controller-gen.
// Cada tipo que precisa ser armazenado no Kubernetes deve implementar DeepCopyObject.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *DeployPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DeployPolicy) DeepCopy() *DeployPolicy {
	if in == nil {
		return nil
	}
	out := new(DeployPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *DeployPolicy) DeepCopyInto(out *DeployPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeployPolicySpec contém só tipos primitivos (bool) — cópia por valor é suficiente.
func (in *DeployPolicySpec) DeepCopyInto(out *DeployPolicySpec) {
	*out = *in
}

func (in *DeployPolicyStatus) DeepCopyInto(out *DeployPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		// metav1.Condition é composto só de value types (strings, int64, Time),
		// então copy() é suficiente — não há ponteiros internos para clonar.
		*out = make([]metav1.Condition, len(*in))
		copy(*out, *in)
	}
}

func (in *DeployPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DeployPolicyList) DeepCopy() *DeployPolicyList {
	if in == nil {
		return nil
	}
	out := new(DeployPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *DeployPolicyList) DeepCopyInto(out *DeployPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeployPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}
